### ISSUE TITLE
咋回事大佬

### ISSUE THREAD

**Issue by 303562915** [Mesto74/ECUT_TodayCampus#2]
咋回事大佬
Traceback (most recent call last):
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\index.py", line 29, in main
    msg = working(user)
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\index.py", line 47, in working
    today.login()
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\todayLoginService.py", line 92, in login
    self.checkLogin()
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\todayLoginService.py", line 86, in checkLogin
    self.session.cookies = self.loginEntity.login()
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\login\casLogin.py", line 40, in login
    soup = BeautifulSoup(str(form[1]), 'lxml')
IndexError: list index out of range

23:49:03 list index out of range
23:49:03 正在发送邮件通知
Traceback (most recent call last):
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\index.py", line 29, in main
    msg = working(user)
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\index.py", line 47, in working
    today.login()
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\todayLoginService.py", line 92, in login
    self.checkLogin()
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\todayLoginService.py", line 86, in checkLogin
    self.session.cookies = self.loginEntity.login()
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\login\casLogin.py", line 40, in login
    soup = BeautifulSoup(str(form[1]), 'lxml')
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\python\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "H:\python\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "H:\python\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "H:\python\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "H:\python\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "H:\python\lib\site-packages\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "H:\python\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x0000021ABCE3F0D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\python\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "H:\python\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "H:\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.ruoli.cc', port=443): Max retries exceeded with url: /mail/sendMail?reciever=3340181255%40qq.com&title=%5Berror%5D%E4%BB%8A%E6%97%A5%E6%A0%A1%E5%9B%AD%E9%80%9A%E7%9F%A5&content=%5B2024-10-25+23%3A49%3A03%5Dlist+index+out+of+range (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021ABCE3F0D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\index.py", line 102, in <module>
    main()
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\index.py", line 34, in main
    msg = rl.send('error', msg)
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\actions\rlMessage.py", line 75, in send
    return self.sendMail(status, msg)
  File "C:\Users\s30356\Desktop\py2024\ECUT_TodayCampus-main\actions\rlMessage.py", line 37, in sendMail
    res = requests.post(url=self.apiUrl, params=params).json()
  File "H:\python\lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "H:\python\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "H:\python\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "H:\python\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "H:\python\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.ruoli.cc', port=443): Max retries exceeded with url: /mail/sendMail?reciever=3340181255%40qq.com&title=%5Berror%5D%E4%BB%8A%E6%97%A5%E6%A0%A1%E5%9B%AD%E9%80%9A%E7%9F%A5&content=%5B2024-10-25+23%3A49%3A03%5Dlist+index+out+of+range (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000021ABCE3F0D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by Mesto74** [comment]
小伙子 这项目n年没维护了 另寻他法吧
